package pg.exception;

public enum ErrorCode {

    LOAD_BUNDLE,
    LOAD_PROPERTIES, 
    SAVE_PROPERTIES, 
    NULL_ARGUMENT, 
    NO_ARGUMENTS, 
    PREPARATION,
    NULL_ERROR_CODE,
    BUTTON_IMG,
    DESTINATION_NOT_CREATED,
    LAUNCH_PROGRAM;
}
